### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by asynts** [asynts/lua#1]
# 2018.08.29
- [ ] make `reader.cpp` a header, `lua/intern/reader.hpp`
- [ ] remove `helper.cpp`
- [ ] rename `Tok::INT` to `Tok::NUMBER`
- [ ] start refactoring the short string literal code

# Future
- [ ] parse long string literals
